
font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  size: 13.5

# https://github.com/huyvohcmc/tender-alacritty
colors:
  primary:
    background: '0x282828'
    foreground: '0xeeeeee'
  normal:
    black: '0x282828'
    red: '0xf43753'
    green: '0xc9d05c'
    yellow: '0xffc24b'
    blue: '0xb3deef'
    magenta: '0xd3b987'
    cyan: '0x73cef4'
    white: '0xeeeeee'
  bright:
    black: '0x4c4c4c'
    red: '0xf43753'
    green: '0xc9d05c'
    yellow: '0xffc24b'
    blue: '0xb3deef'
    magenta: '0xd3b987'
    cyan: '0x73cef4'
    white: '0xfeffff'

# https://github.com/zellij-org/zellij/issues/2051#issuecomment-1461519892
window:
  option_as_alt: Both

