
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew avrdude
brew azure-cli
brew boost
brew cairo
brew cmake
brew coreutils
brew dfu-programmer
brew dfu-util
brew fdk-aac
brew ffmpeg --with-fdk-aac --with-freetype --with-libass
brew fish
brew fontconfig
brew freetype
brew fribidi
brew fzf
brew gcc
brew gdbm
brew gettext
brew ghq
brew glib
brew gmp
brew gnu-sed
brew go
brew graphite2
brew harfbuzz
brew htop
brew hub
brew icu4c
brew isl
brew jemalloc
brew jq
brew kubernetes-helm
brew lame
brew libass
brew libelf
brew libevent
brew libffi
brew libftdi0
brew libhid
brew libidn2
brew libmpc
brew libogg
brew libpng
brew libtermkey
brew libunistring
brew libusb
brew libusb-compat
brew libuv
brew libvorbis
brew libvpx
brew libvterm
brew libyaml
brew llvm
brew lua
brew lua@5.1
brew luajit
brew luarocks
brew mas
brew mpfr
brew msgpack
brew nasm
brew ncurses
brew neovim --HEAD
brew nmap
brew node-build
brew nodebrew
brew nodenv
brew oniguruma
brew openssl
brew opus
brew pcre
brew pcre2
brew peco
brew perl
brew pipenv
brew pixman
brew pkg-config
brew pyenv
brew python
brew python@2
brew qt
brew rbenv
brew rbenv-communal-gems
brew readline
brew reattach-to-user-namespace
brew redis
brew ripgrep
brew ruby
brew ruby-build
brew sdl2
brew snappy
brew sqlite
brew texi2html
brew theora
brew tig
brew tmux
brew todo-txt
brew tree
brew unibilium
brew vim
brew wget
brew x264
brew x265
brew xonsh
brew xvid
brew xz

tap homebrew/cask-fonts
cask font-hack-nerd-font

tap homebrew/cask
cask alacritty
cask minikube

tap caskroom/cask
cask kindlegen

tap neovim/neovim

tap osx-cross/avr
brew avr-gcc@7

tap px4/px4
brew gcc-arm-none-eabi

tap rcmdnk/file
brew brew-file

tap universal-ctags/universal-ctags
brew universal-ctags --HEAD

# Other Cask applications
cask oni

# App Store applications
appstore 1333542190 com.agilebits.onepassword7 (7.3.2)
appstore 497799835 com.apple.dt.Xcode (10.3)
appstore 682658836 com.apple.garageband10 (10.3.2)
appstore 408981434 com.apple.iMovieApp (10.1.12)
appstore 409183694 com.apple.iWork.Keynote (9.1)
appstore 409203825 com.apple.iWork.Numbers (6.1)
appstore 409201541 com.apple.iWork.Pages (8.1)
appstore 461369673 com.coppertino.Vox (3.3.10)
appstore 1044549675 com.eltima.elmedia6.mas (7.4)
appstore 714196447 com.fabriceleyne.menubarstats (2.2.6)
appstore 483820530 com.joshjacob.qrjournal (1.7.1)
appstore 1429033973 com.kyome.RunCat (4.6)
appstore 414568915 com.manytricks.KeyCodes (2.1)
appstore 528183797 com.rodrigocardoso.Joystick-Mapper (1.1.3)
appstore 803453959 com.tinyspeck.slackmacgap (4.0.1)
appstore 1160374471 de.APPenzeller.PiPifier (1.2.4)
appstore 1206246482 djhan.EdgeView-2 (2.819)
appstore 539883307 jp.naver.line.mac (5.18.2)
