# ------------------------------------------------------------------------------
# insert mode
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
  source ~/.config/nvim/plugins/deoplete.rc.vim
'''

# ------------------------------------------------------------------------------
# focus lost & cursor lost
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'tpope/vim-repeat'
on_event = ['FocusLost', 'CursorLost']

# ------------------------------------------------------------------------------
# filetype
# ------------------------------------------------------------------------------

# coffee ------------------------------------------------------------------------

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# ejs ---------------------------------------------------------------------------

[[plugins]]
repo = 'nikvdp/ejs-syntax'
on_ft = 'ejs'

# fish --------------------------------------------------------------------------

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

# go ----------------------------------------------------------------------------

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
  let g:go_test_show_name = 1
  let g:go_list_type = "quickfix"
  let g:go_fmt_command = "goimports"
  let g:go_auto_type_info = 1
  let g:go_auto_sameids = 1
  let g:go_highlight_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_extra_types = 1
  let g:go_highlight_generate_tags = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
depends = 'deoplete.nvim'
build = 'make'
hook_source = '''
  let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
  let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
  let g:deoplete#sources#go#package_dot = 1
  let g:deoplete#sources#go#pointer = 1
'''

# html --------------------------------------------------------------------------

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'vue']

# json --------------------------------------------------------------------------

[[plugins]]
repo = 'leshill/vim-json'
on_ft = 'json'

# python ------------------------------------------------------------------------

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = 'deoplete.nvim'
on_ft = 'python'
hook_source = '''
  if has('unix')
    let g:python_host_prog = '/usr/bin/python2'
    let g:python3_host_prog = '/usr/bin/python3'
  endif
  if has('mac')
    let g:python_host_prog = '/usr/local/bin/python2'
    let g:python3_host_prog = '/usr/local/bin/python3'
  endif
'''

[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'bps/vim-textobj-python'
on_ft = 'python'
depends = ['vim-textobj-user']

# ruby --------------------------------------------------------------------------

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

# tex ---------------------------------------------------------------------------

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

# toml -------------------------------------------------------------------------

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# typescript --------------------------------------------------------------------

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

# vim --------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

# vue ---------------------------------------------------------------------------

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
