# ------------------------------------------------------------------------------
# focus lost & cursor lost
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'tpope/vim-repeat'
on_event = ['FocusLost', 'CursorLost']

# ------------------------------------------------------------------------------
# filetype
# ------------------------------------------------------------------------------

# coffee ------------------------------------------------------------------------

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# ejs ---------------------------------------------------------------------------

[[plugins]]
repo = 'nikvdp/ejs-syntax'
on_ft = 'ejs'

# fish --------------------------------------------------------------------------

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

# html/xml -----------------------------------------------------------------------

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xml', 'vue']

# json --------------------------------------------------------------------------

[[plugins]]
repo = 'leshill/vim-json'
on_ft = 'json'

# markdown ----------------------------------------------------------------------

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = 'markdown'

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = 'markdown'
hook_source = '''
  let g:markdown_enable_mappings = 1
  let g:markdown_enable_spell_checking = 0
  let g:markdown_mapping_switch_status = '<Leader>o'
'''

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'
depends = 'open-browser.vim'

# mustache ----------------------------------------------------------------------

[[plugins]]
repo = 'mustache/vim-mustache-handlebars'
on_ft = 'mustache'

# python ------------------------------------------------------------------------

[[plugins]]
repo = 'bps/vim-textobj-python'
on_ft = 'python'
depends = ['vim-textobj-user']

# ruby --------------------------------------------------------------------------

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

# toml -------------------------------------------------------------------------

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# typescript --------------------------------------------------------------------

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

# vim --------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

# vue ---------------------------------------------------------------------------

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
