# ------------------------------------------------------------------------------
# plugin manager
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/dein.vim'

# ------------------------------------------------------------------------------
# color
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'rhysd/vim-color-spring-night'
hook_add = '''
  au MyAutoCmd VimEnter * nested colorscheme spring-night
  au MyAutoCmd VimEnter * highlight CursorLine cterm=none
  " For Vim 7.4.1799 or later
  if has('termguicolors')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
  elseif has('nvim')
    " For Neovim 0.1.5 or later
    set termguicolors
  endif
'''

# ------------------------------------------------------------------------------
# basic
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star-with-echo)
  nmap # <Plug>(anzu-sharp-with-echo)
  nmap <silent> <Esc><Esc> :nohlsearch<CR><Plug>(anzu-clear-search-status)
'''

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
  nmap p <Plug>(yankround-p)
  nmap P <Plug>(yankround-P)
  nmap gp <Plug>(yankround-gp)
  nmap gP <Plug>(yankround-gP)
  nmap <C-p> <Plug>(yankround-prev)
  nmap <C-n> <Plug>(yankround-next)
'''

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
  let g:tcomment_maps = 0
  nmap <silent><Leader>i :TComment<CR>
  vmap <silent><Leader>i :TComment<CR>
'''

[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
  nmap <Leader>h <Plug>(quickhl-manual-this)
  nmap <Leader>H <Plug>(quickhl-manual-reset)
'''

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
hook_add = '''
  nmap <Leader>j :SplitjoinJoin<CR>
  nmap <Leader>s :SplitjoinSplit<CR>
'''

# ------------------------------------------------------------------------------
# linter
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
  source ~/.config/nvim/plugins/neomake.rc.vim
'''

# ------------------------------------------------------------------------------
# filer
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = 'denite.nvim'

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeMinimalUI = 1
  let g:NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = 'nerdtree'
hook_add = '''
  nnoremap <silent> <Leader>e :NERDTreeTabsToggle<CR>
'''

# ------------------------------------------------------------------------------
# powerline
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'
depends = 'vim-fugitive' 
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'spring_night'
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_guide_size = 1
  let g:indent_guides_auto_colors = 0
  let g:indent_guides_default_mapping = 0
  au MyAutoCmd VimEnter,ColorScheme * hi IndentGuidesOdd ctermbg=237
  au MyAutoCmd VimEnter,ColorScheme * hi IndentGuidesEven ctermbg=240
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_map_keys = 0
'''

# ------------------------------------------------------------------------------
# terminal
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  source ~/.config/nvim/plugins/neoterm.rc.vim
'''

# ------------------------------------------------------------------------------
# extension for vim
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

# ------------------------------------------------------------------------------
# filetype
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/context_filetype.vim'
