# ------------------------------------------------------------------------------
# insert mode
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  " <TAB>: completion.
  inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ deoplete#manual_complete()
  function! s:check_back_space() abort "{{{
    let l:col = col('.') - 1
    return !l:col || getline('.')[l:col - 1]  =~ '\s'
  endfunction"}}}

  " <S-TAB>: completion back.
  inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"

  " <BS>: close popup and delete backword char.
  inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"
  if !exists('g:deoplete#omni_patterns')
    let g:deoplete#omni_patterns = {}
  endif
  let g:deoplete#omni_patterns.r = '[[:alnum:].\\]\+'
'''

# ------------------------------------------------------------------------------
# focus lost & cursor lost
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'tpope/vim-repeat'
on_event = ['FocusLost', 'CursorLost']

# ------------------------------------------------------------------------------
# filetype
# ------------------------------------------------------------------------------

# coffee ------------------------------------------------------------------------

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# ejs ---------------------------------------------------------------------------

[[plugins]]
repo = 'nikvdp/ejs-syntax'
on_ft = 'ejs'

# fish --------------------------------------------------------------------------

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

# go ----------------------------------------------------------------------------

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
  let g:go_test_show_name = 1
  " let g:go_list_type = "quickfix"
  let g:go_fmt_command = "goimports"
  " let g:go_auto_type_info = 1
  " let g:go_auto_sameids = 1
  " let g:go_highlight_types = 1
  " let g:go_highlight_fields = 1
  " let g:go_highlight_functions = 1
  " let g:go_highlight_methods = 1
  " let g:go_highlight_operators = 1
  " let g:go_highlight_extra_types = 1
  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0 " let g:go_highlight_generate_tags = 1
'''

# html --------------------------------------------------------------------------

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'vue']

# json --------------------------------------------------------------------------

[[plugins]]
repo = 'leshill/vim-json'
on_ft = 'json'

# markdown ----------------------------------------------------------------------

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = 'markdown'

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = 'markdown'
hook_source = '''
  let g:markdown_enable_mappings = 1
  let g:markdown_enable_spell_checking = 0
  let g:markdown_mapping_switch_status = '<Leader>o'
'''

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'
depends = 'open-browser.vim'

# python ------------------------------------------------------------------------

[[plugins]]
repo = 'bps/vim-textobj-python'
on_ft = 'python'
depends = ['vim-textobj-user']

# ruby --------------------------------------------------------------------------

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

# tex ---------------------------------------------------------------------------

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

# toml -------------------------------------------------------------------------

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# typescript --------------------------------------------------------------------

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

# vim --------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

# vue ---------------------------------------------------------------------------

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
