# ------------------------------------------------------------------------------
# plugin manager
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/dein.vim'

# ------------------------------------------------------------------------------
# UI
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
hook_add = '''
  set background=dark
  colorscheme spring-night
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'spring_night'
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_guide_size = 1
  let g:indent_guides_auto_colors = 0
  let g:indent_guides_default_mapping = 0
  autocmd VimEnter,ColorScheme * :hi IndentGuidesOdd ctermbg=234
  autocmd VimEnter,ColorScheme * :hi IndentGuidesEven ctermbg=235
'''

# ------------------------------------------------------------------------------
# basic
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star-with-echo)
  nmap # <Plug>(anzu-sharp-with-echo)
  nmap <silent> <Esc><Esc> :nohlsearch<CR><Plug>(anzu-clear-search-status)
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
  let g:tcomment_maps = 0
  nmap <silent> <Leader>i :TComment<CR>
  vmap <silent> <Leader>i :TComment<CR>
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
  nmap p <Plug>(yankround-p)
  nmap P <Plug>(yankround-P)
  nmap gp <Plug>(yankround-gp)
  nmap gP <Plug>(yankround-gP)
  nmap <C-p> <Plug>(yankround-prev)
  nmap <C-n> <Plug>(yankround-next)
'''

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
hook_add = '''
  nmap <silent> <Leader>j :SplitjoinJoin<CR>
  nmap <silent> <Leader>s :SplitjoinSplit<CR>
'''

[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
  nmap <Leader>h <Plug>(quickhl-manual-this)
  nmap <Leader>H <Plug>(quickhl-manual-reset)
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

# ------------------------------------------------------------------------------
# filer
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  nmap <silent> <Leader>ff :Denite<Space>file_rec<CR>
  nmap <silent> <Leader>fg :Denite<Space>grep<CR>
  nmap <silent> <Leader>fm :Denite<Space>file_mru<CR>
  nmap <silent> <Leader>fj :DeniteBufferDir<Space>file<Space>file:new<CR>
  nmap <silent> <Leader>fb :Denite<Space>buffer<CR>
  nmap <silent> <Leader>fq :Denite<Space>help<CR>
  nmap <silent> <Leader>fl :Denite<Space>line<CR>
  nmap <silent> <Leader>ft :Denite<Space>tag<CR>
  nmap <silent> <Leader>fu :Denite<Space>menu<CR>
  nmap <silent> <Leader>fy :Denite<Space>neoyank<CR>
  nmap <silent> <Leader>fc :Denite<Space>codeAction<CR>

  " replace grep into ripgrep
  if executable('rg')
    call denite#custom#var('file_rec', 'command', ['rg', '--files', '--glob', '!.git'])
    call denite#custom#var('grep', 'command', ['rg'])
  endif
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])

  " change matcher
  call denite#custom#source('file_rec', 'matchers', ['matcher_cpsm', 'matcher_ignore_globs'])

  " customize ignore globs
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
        \ [
        \ '.git/', 'build/', '__pycache__/',
        \ 'images/', '*.o', '*.make',
        \ '*.min.*', 'imgs/',
        \ 'img/', 'fonts/'])

  " denite/insert モードのときは，C-,↑↓ で移動できるようにする
  call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
  call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')
  call denite#custom#map('insert', "<Down>", '<denite:move_to_next_line>')
  call denite#custom#map('insert', "<Up>", '<denite:move_to_previous_line>')

  " tabopen や vsplit のキーバインドを割り当て
  call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
  call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
  call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = 'denite.nvim'

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'
depends = 'denite.nvim'

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

# ------------------------------------------------------------------------------
# filetype
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# ------------------------------------------------------------------------------
# LSP
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = './install.sh'
hook_add = '''
  let g:LanguageClient_serverCommands = {}
  let g:LanguageClient_serverCommands["python"] = ['pyls']
  let g:LanguageClient_serverCommands["go"] = ['go-langserver']
  let g:LanguageClient_serverCommands["javascript"] = ['javascript-typescript-langserver']
  let g:LanguageClient_serverCommands["typescript"] = ['javascript-typescript-langserver']
  let g:LanguageClient_hoverPreview = "Never"
'''

# ------------------------------------------------------------------------------
# linter
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'w0rp/ale'

# ------------------------------------------------------------------------------
# git
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'
depends = 'vim-fugitive' 

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_map_keys = 0
'''

# ------------------------------------------------------------------------------
# extension for vim
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"
