# ------------------------------------------------------------------------------
# plugin manager
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  command! UpdatePlugins :call dein#update()
'''

# ------------------------------------------------------------------------------
# UI
# ------------------------------------------------------------------------------ 

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  set termguicolors
  syntax enable
  colorscheme tender
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'tender'
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  set guifont=Hack\ Nerd\ Font\ Mono:h11
'''

# ------------------------------------------------------------------------------
# basic
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star-with-echo)
  nmap # <Plug>(anzu-sharp-with-echo)
  " remove hilight & preview
  nmap <silent> <Esc><Esc> :pclose<CR>:nohlsearch<CR><Plug>(anzu-clear-search-status)
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
  let g:tcomment_maps = 0
  nmap <silent> <Leader>i :TComment<CR>
  vmap <silent> <Leader>i :TComment<CR>
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
  nmap p <Plug>(yankround-p)
  nmap P <Plug>(yankround-P)
  nmap gp <Plug>(yankround-gp)
  nmap gP <Plug>(yankround-gP)
  nmap <C-p> <Plug>(yankround-prev)
  nmap <C-n> <Plug>(yankround-next)
'''

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
hook_add = '''
  nmap <silent> <Leader>j :SplitjoinJoin<CR>
  nmap <silent> <Leader>s :SplitjoinSplit<CR>
'''

[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
  nmap <Leader>h <Plug>(quickhl-manual-this)
  nmap <Leader>H <Plug>(quickhl-manual-reset)
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

# ------------------------------------------------------------------------------
# filer
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  nmap <silent> <Leader>ff :Denite<Space>file_rec<CR>
  nmap <silent> <Leader>fg :Denite<Space>grep<CR>
  nmap <silent> <Leader>fm :Denite<Space>file_mru<CR>
  nmap <silent> <Leader>fj :DeniteBufferDir<Space>file<Space>file:new<CR>
  nmap <silent> <Leader>fb :Denite<Space>buffer<CR>
  nmap <silent> <Leader>fq :Denite<Space>help<CR>
  nmap <silent> <Leader>fl :Denite<Space>line<CR>
  nmap <silent> <Leader>ft :Denite<Space>tag<CR>
  nmap <silent> <Leader>fu :Denite<Space>menu<CR>
  nmap <silent> <Leader>fy :Denite<Space>neoyank<CR>
  nmap <silent> <Leader>fc :Denite<Space>codeAction<CR>

  " replace grep into ripgrep
  if executable('rg')
    call denite#custom#var('file_rec', 'command', ['rg', '--hidden', '--files', '--glob', '!.git'])
    call denite#custom#var('grep', 'command', ['rg', '--hidden'])
  endif
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])

  " change matcher
  call denite#custom#source('file_rec', 'matchers', ['matcher_cpsm', 'matcher_ignore_globs'])

  " customize ignore globs
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
        \ [
        \ '.git/', 'build/', '__pycache__/',
        \ 'images/', '*.o', '*.make',
        \ '*.min.*', 'imgs/',
        \ 'img/', 'fonts/'])

  " denite/insert モードのときは，C-,↑↓ で移動できるようにする
  call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
  call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')
  call denite#custom#map('insert', "<Down>", '<denite:move_to_next_line>')
  call denite#custom#map('insert', "<Up>", '<denite:move_to_previous_line>')

  " tabopen や vsplit のキーバインドを割り当て
  call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
  call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
  call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = 'denite.nvim'

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'
depends = 'denite.nvim'

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeShowHidden = 1
  let g:NERDTreeMinimalUI = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = 'nerdtree'
hook_add = '''
  nmap <Leader>n :NERDTreeTabsToggle<CR>
  nmap <Leader>m :NERDTreeTabsFind<CR>
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

# ------------------------------------------------------------------------------
# filetype
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# ------------------------------------------------------------------------------
# LSP
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = './install.sh'
hook_add = '''
  let g:LanguageClient_serverCommands = {}
  let g:LanguageClient_serverCommands['python'] = ['pyls']
  let g:LanguageClient_serverCommands['javascript'] = ['javascript-typescript-langserver']
  let g:LanguageClient_serverCommands['typescript'] = ['javascript-typescript-langserver']
  let g:LanguageClient_serverCommands['go'] = ['golsp', '-mode', 'stdio']
  let g:LanguageClient_serverCommands['sh'] = ['bash-language-server', 'start']
  let g:LanguageClient_serverCommands['ruby'] = ['solargraph', 'stdio']
  let g:LanguageClient_serverCommands['dockerfile'] = ['docker-langserver', '--stdio']
  let g:LanguageClient_serverCommands['sql'] = ['sql-language-sever', 'up', '--method', 'stdio']
  let g:LanguageClient_hoverPreview = 'Always'
  let g:LanguageClient_loadSettings = 1
  let g:LanguageClient_hasSnippetSupport = 1
  let g:LanguageClient_completionPreferTextEdit = 1
  nnoremap <silent><Leader>k :call LanguageClient#textDocument_hover()<CR>
  nnoremap <silent><Leader>d :call LanguageClient#textDocument_definition()<CR>
  nnoremap <silent><Leader>R :call LanguageClient#textDocument_rename()<CR>
  nnoremap <silent><Leader>u :call LanguageClient#textDocument_references()<CR>
  nnoremap <silent><Leader>F :call LanguageClient#textDocument_formatting()<CR>
  nnoremap <silent><Leader>A :call LanguageClient#textDocument_codeAction()<CR>
  nnoremap <silent><Leader>s :call LanguageClient#textDocument_documentSymbol()<CR>
'''

# ------------------------------------------------------------------------------
# snippets
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# ------------------------------------------------------------------------------
# linter
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_error = '✖'
  let g:ale_sign_warning = '⚠'
  let g:ale_virtualtext_cursor = 1
  let g:ale_virtualtext_prefix = '▶ '
'''

# ------------------------------------------------------------------------------
# git
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'
depends = 'vim-fugitive' 

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_map_keys = 0
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/open-browser-github.vim'
depends = 'open-browser.vim'

# ------------------------------------------------------------------------------
# extension for vim
# ------------------------------------------------------------------------------

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

[[plugins]]
repo = 'vim-jp/vital.vim'
merged = 0

[[plugins]]
repo = 'lambdalisue/vital-Whisky'
