shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"
apply = ["defer"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.zsh-better-npm-completion]
github = "lukechilds/zsh-better-npm-completion"
apply = ["defer"]

[plugins.aws_zsh_completer]
remote = "https://raw.githubusercontent.com/aws/aws-cli/v2/bin/aws_zsh_completer.sh"
apply = ["defer"]

[plugins.sync]
local = "~/dotfiles/config/zsh"
use = ["sync.zsh"]

[plugins.async]
local = "~/dotfiles/config/zsh"
use = ["async.zsh"]
apply = ["defer"]
